[alias]     # command aliases
demo = "run --release --package demo --target riscv32imc-esp-espidf"
server = "run --package server --target x86_64-unknown-linux-gnu"

[unstable]
build-std = ["std", "panic_abort"]

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --baud=921600" # Select this runner for espflash v3.x.x
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[env]
EVAC_SERVER_CONFIG = "data/server.json"
MCU="esp32c3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.2"

# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174
CRATE_CC_NO_DEFAULTS = "1"
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"
ESP_IDF_SYS_ROOT_CRATE = "demo"
ESP_IDF_PATH_ISSUES = "warn"
