[package]
name = "test_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
rmp-serde = { version = "1.3.0"}
shared = { path = "../shared" }
anyhow = "1"